theme: theme
title: Reconnect
author: Jason Morley
email: support@jbmorley.co.uk
description: Psion Connectivity for macOS
url: "https://reconnect.jbmorley.co.uk"
baseurl: ""
repository: https://github.com/inseven/reconnect
copyright: 2024-2026 <a href="https://jbmorley.co.uk/about">Jason Morley</a>

navigation:
  - title: Reconnect
    href: /
  - title: Documentation
    href: /docs
  - title: Releases
    href: /releases
  - title: GitHub
    href: https://github.com/inseven/reconnect
  - title: Donate
    href: https://jbmorley.co.uk/support/

footer:
  - title: Privacy Policy
    href: /privacy-policy
  - title: License
    href: /license
  - title: More Software
    href: https://jbmorley.co.uk/software/

plugins:
  - jekyll-environment-variables
  - jekyll-feed
  - jekyll-gfm-admonitions
  - jekyll-image-size
  - jekyll-toc
destination: ../_site

toc:
  ordered_list: true

defaults:
  - values:
      layout: "page"
  - scope:
      path: "docs"
    values:
      layout: "documentation"
      toc: true
      shows_title: true
